### PR TITLE
refactor: add log if token connect fails

### LINKED ISSUE #280: GH Enterprise problem
When I try any command I get the following warning:
'Please setup your Github Personal Access Token and open a GitHub project in your workspace'

I've got both GitHub Enterprise and GitHub tokens set up using the extension command ('Set up GitHub Enterprise Token...') and got only one project open in the workspace which is on that GHE.

### PR DESCRIPTION
**Pull request by KnisterPeter**
Closes #280

### CODE REVIEW

**Comment by KnisterPeter** [comment]
@marek-nogiec It would be great if you can build and test this branch and give me the output of the error panel. To do that this steps are required:

1. checkout this repo
1. run `npm install -g vsce`
1. run `vsce package`
1. run `code --install-extension <path/to/vsce-package>`

Then try to execute a command, open the output panel (`Toggle Output`  command) and switch to the `github` tab. Any information there would be really helpful for me.

**Comment by marek-nogiec** [comment]
Sadly, nothing new:
I still get the warning: `Please setup your Github Personal Access Token and open a GitHub project in your workspace`

and the log is:
```
Visual Studio Code GitHub Extension
git config --local --get remote.origin.url
git --version
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
git config --local --get remote.origin.url
```

**Comment by marek-nogiec** [comment]
@KnisterPeter 
```
Visual Studio Code GitHub Extension
git config --local --get remote.origin.url
git --version
git config --local --get remote.origin.url
Failed to connect to provier uri file:///Users/marek/www/my-repo "No token"
```

**Comment by KnisterPeter** [comment]
@marek-nogiec Can you try again. There should be a bit more information in the error.

> Failed to connect to provier uri file:///Users/marek/www/my-repo "No token"

But as you already can see in the output, the token you configured is not found.
When setup a github enterprise token, the token is associated to a specific host. You entered it during token setup. That hostname does not match the given input.
In the current commit the hostname a token is searched for is contained in the error message.

**Comment by marek-nogiec** [comment]
@KnisterPeter ok, I'm an idiot, I didn't notice the first thing I had to input is the hostname and not the token itself (coz I probably assumed it's gonna resolve hostname from the remote). Now that I configured it correctly it works. So sorry for wasting time and thanks for debugging this! Happy holidays!

**Comment by KnisterPeter** [comment]
@marek-nogiec Your welcome. I'm happy to help and glad its working now. 🚀

**Comment by KnisterPeter** [comment]
Oh, and as well happy holidays! 😃

**Pull request merged**
